---
apiVersion: policy.open-cluster-management.io/v1
kind: PolicyGenerator
metadata:
  name: tenancy-ac-managed
placementBindingDefaults:
  name: binding-tenancy-managed-ac
policyDefaults:
  categories:
    - AC Access Control
  controls:
    - Enforce Tenant Access
  namespace: policies
  policySets:
    - tenancy-managed-access-control
  remediationAction: enforce
  severity: high
  standards:
    - Multi-Tenant Isolation
  complianceType: mustonlyhave
  consolidateManifests: false

policies:
  - name: tenancy-managed-custom-clusterroles
    controls:
      - Deploy Tenant Least-Privilege ClusterRoles for Tenant Namespaces
    complianceType: musthave
    manifests:
      - path: rbac/custom-clusterroles.yaml

policySets:
  - name: tenancy-managed-access-control
    description: Managed cluster least-privilege ClusterRoles for tenant namespace access (bound via MCRA from hub)
    placement:
      placementName: policies-placement-managed-clusters
