---
apiVersion: policy.open-cluster-management.io/v1
kind: PolicyGenerator
metadata:
  name: tenancy-ac-managed
placementBindingDefaults:
  name: binding-tenancy-managed-ac
policyDefaults:
  categories:
    - AC Access Control
  controls:
    - Enforce Tenant Access
  namespace: policies
  policySets:
    - tenancy-managed-access-control
  remediationAction: enforce
  severity: high
  standards:
    - Multi-Tenant Isolation
  complianceType: mustonlyhave
  consolidateManifests: false

policies:
  - name: tenancy-managed-namespace-rbac
    controls:
      - Enforce Namespace RBAC for Tenant-Admin and Tenant-Operator
    dependencies:
      - name: tenancy-managed-tenant-replication
        namespace: tenancies
        compliance: Compliant
    consolidateManifests: false
    manifests:
      - path: rbac/managed-rolebindings.yaml

policySets:
  - name: tenancy-managed-access-control
    description: Managed cluster namespace RoleBindings granting Tenant-Admin and Tenant-Operator access
    placement:
      placementName: policies-placement-managed-clusters
