---
apiVersion: policy.open-cluster-management.io/v1
kind: PolicyGenerator
metadata:
  name: policy-hub-tenancy-access-control
placementBindingDefaults:
  name: binding-hub-tenancy-access-control
policyDefaults:
  categories:
    - CM Configuration Management
  controls:
    - CM-6 Configuration Settings
  namespace: tenancies
  policySets:
    - tenancy-managed-configuration
  remediationAction: enforce
  severity: high
  standards:
    - NIST SP 800-53
  complianceType: mustonlyhave
  consolidateManifests: false

policies:
  - name: policy-tenant-crd-create
    manifests:
    - path: tenancy/tenant-crd.yaml
  - name: policy-tenant-bridge
    manifests:
    - path: tenancy/bridge-tenants.yaml
    dependencies:
      - name: policy-tenant-crd-create

policySets:
  - name: tenancy-hub-configuration-management
    description: Hub-side tenant configuration management
    placement:
      placementName: placement-hub-clusters