apiVersion: policy.open-cluster-management.io/v1
kind: PolicyGenerator
metadata:
  name: policy-managed-cluster-tenancy
placementBindingDefaults:
  name: binding-tenancies-placement-managed-clusters
policyDefaults:
  namespace: tenancies
  policySets:
    - policyset-managed-tenancy
  categories:
    - SC System and Communications Protection
  controls:
    - Tenant Isolation
  standards:
    - NIST SP 800-53
  severity: high
  remediationAction: enforce
  consolidateManifests: false
  orderManifests: true
policies:
  - name: policy-managed-cluster-tenant-crd-create
    manifests:
    - path: tenancy/tenant-crd.yaml
    - path: tenancy/tenancies-namespace.yaml
  - name: policy-tenant-bridge-to-managed-clusters
    manifests:
    - path: tenancy/bridge-tenants.yaml
    dependencies:
      - name: policy-managed-cluster-tenant-crd-create
policySets:
  - name: policyset-managed-tenancy
    description: Managed cluster tenancy objects bridged to managed clusters
    placement:
      placementName: tenancies-placement-managed-clusters

