---
apiVersion: dusty-seahorse.io/v1alpha1
kind: Tenant
metadata:
  name: startrek
  namespace: tenancies
spec:
  displayName: "Star Trek"
  owner: platform-team@example.com
  adminGroup: startrek-admins
  operatorGroup: startrek-operators

  resourceQuota:
    cpu: "86"
    memory: "332Gi"
    pods: "15"
    storage: "2000Gi"

  vmQuota:
    cpu: "80"
    memory: "320Gi"

  limitRange:
    maxCpu: "32"
    maxMemory: "128Gi"
    maxStorage: "1Ti"

  network:
    udnSubnet: "10.0.2.0/24"
    metallb:
      myASN: 64500
      peerASN: 64502
      peerAddress: "192.168.1.2"
      vrf: startrek-vrf
      addresses:
        - "192.168.12.0/24"
