---
apiVersion: rbac.open-cluster-management.io/v1beta1
kind: MulticlusterRoleAssignment
metadata:
  name: TENANT-virt-ROLE
  namespace: policies
spec:
  subject:
    kind: Group
    name: TENANT-GROUP
  roleAssignments:
  - name: TENANT-virt-ROLE-kubevirt
    clusterRole: kubevirt.io:ROLE
    targetNamespaces:
    - TENANT-NAMESPACE
    clusterSelection:
      type: placements
      placements:
      - name: placement-managed-clusters
        namespace: policies
  - name: TENANT-virt-ROLE-extended
    clusterRole: acm-vm-extended:ROLE_EXTENDED
    targetNamespaces:
    - TENANT-NAMESPACE
    clusterSelection:
      type: placements
      placements:
      - name: placement-managed-clusters
        namespace: policies