---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: tenancy-access-control
  namespace: openshift-gitops
spec:
  destination:
    namespace: policies
    server: https://kubernetes.default.svc
  project: tenancy-policy
  source:
    path: policygen/AC-Access-Control
    repoURL: https://github.com/ngner/tenancy-by-acm-policy.git
    targetRevision: master
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
    automated:
      prune: false
      selfHeal: false
