---

## This application renders the Tenant CRs and the Tenant CRD in the tenancies namespace.
# This will GitOps the tenancy creation.  One could create the tenants by GUI then copy to the tenancies folder.

apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: tenancy-base
  namespace: openshift-gitops
spec:
  destination:
    namespace: tenancies
    server: https://kubernetes.default.svc
  project: tenancy-policy
  source:
    path: tenancies
    repoURL: https://github.com/ngner/tenancy-by-acm-policy.git
    targetRevision: master
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
    automated:
      prune: true
      selfHeal: true
