---
apiVersion: cluster.open-cluster-management.io/v1beta1
kind: Placement
metadata:
  name: tenancies-placement-hub-clusters
  namespace: tenancies
spec:
  predicates:
    - requiredClusterSelector:
        labelSelector:
          matchLabels:
            name: local-cluster
