---
apiVersion: cluster.open-cluster-management.io/v1beta1
kind: Placement
metadata:
  name: placement-hub-clusters
  namespace: tenancies
spec:
  tolerations:
    - key: cluster.open-cluster-management.io/unavailable
      operator: Exists
    - key: cluster.open-cluster-management.io/unreachable
      operator: Exists
  predicates:
    - requiredClusterSelector:
        labelSelector:
          matchLabels:
            name: local-cluster
